#!/system/bin/sh
mount -t tmpfs -o size=200M,nr_inodes=42k,mode=0777 tmpfs /data/data/com.android.chrome/cache
mount -t tmpfs -o size=100M,nr_inodes=42k,mode=0777 tmpfs /data/data/com.android.chrome/code_cache


#!/system/bin/sh
/etc/init.d/mycache.sh
mount -t tmpfs -o size=100M,nr_inodes=42k,mode=0777 tmpfs /data/data/com.kapp.youtube.final/cache
mount -t tmpfs -o size=100M,nr_inodes=42k,mode=0777 tmpfs /data/data/com.kapp.youtube.final/code_cache
com.kapp.youtube.final
com.kapp.youtube.final
